server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=exam-service
spring.cloud.gateway.routes[1].uri=lb://EXAM-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/exams/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[2].id=result-service
spring.cloud.gateway.routes[2].uri=lb://RESULT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/results/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# JWT Security
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
